apiVersion: v1
kind: Service
metadata:
  name: web-nodeport-service
spec:
  selector:
    app: minha-biblioteca 
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 5000  
      nodePort: 31098  
  type: NodePort
